apiVersion: v1
kind: Pod
metadata:
  name: az-devops-job-template
  namespace: buildagent
spec:
  restartPolicy: Never
  containers:
    - name: buildagent
      image: {MYPROFILE}/buildagent:java17
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args: ["./start.sh & sleep 45 && pkill -f 'Agent.Listener'"]
      env:
        - name: POWERTOOLS
          value: "true"
        - name: NODE_VERSION
          value: "20"
        - name: NPM_VERSION
          value: "10"
        - name: KUBECTL
          value: "true"
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: AZP_URL
          valueFrom:
            configMapKeyRef:
              key: url
              name: buildagent-azdo-config
        - name: AZP_POOL
          valueFrom:
            configMapKeyRef:
              key: pool
              name: buildagent-azdo-config
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: buildagent-azdo-auth
